### ISSUE TITLE
Mac M1 support

### ISSUE THREAD

**Issue by LauraWebdev** [AryToNeX/Glasstron#168]
**Describe the bug**
Glasstron seems to not be compatible with Apple M1 Macbooks. When implementing in a clean electron project, it yields a fatal error.

**To Reproduce**
1. Create a new Electron/Electron-Vue project
2. Implement Glasstron as specified in the README
3. Run the dev instance

**Desktop (please complete the following information):**
 - OS: macOS 11.5.1
 - Electron: 2.6.x
 - Processor: Apple M1

**Console Output**
```
 ERROR  Failed to compile with 1 errors

 error  in ./node_modules/glasstron/src/native/linux_x11/x11.js

Module parse failed: Unexpected token (23:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| module.exports = class X11 extends EventEmitter {
| 
> 	display = undefined;
| 
| 	createConnection(){

 @ ./node_modules/glasstron/src/native/linux_x11/index.js 18:10-26
 @ ./node_modules/glasstron/src/platforms/linux.js
 @ ./node_modules/glasstron/src/platforms sync ^\.\/.*\.js$
 @ ./node_modules/glasstron/src/utils.js
 @ ./node_modules/glasstron/src/index.js
 @ ./src/background.js
 @ multi ./src/background.js

 ERROR  Build failed with errors.
error Command failed with exit code 1.
```

**Comment by AryToNeX** [comment]
Note that if you are really using Electron 2.6.x (I believe you aren't though) Glasstron will not work at all. That is too old of a version! I believe it doesn't even have binaries for M1 MacBooks itself.

Anyway, your error is about Webpack not recognizing a language feature that was introduced in ES6 if I am not mistaken.

To fix it, you should make Webpack compile code that uses stuff from a newer ES version than the one it is using right now (also because you'd be missing on other great stuff like optional chaining); but actually you should not bundle Glasstron at all, since it relies on `__dirname`, native modules and `exec()` calls (for Windows, at least).

Please read your error logs before assuming that a project is simply not compatible with an architecture, as it is really misleading to other people who might come across the issue section of this project.

**Comment by LauraWebdev** [comment]
My bad for the confusion, I've written this issue before and the page reloaded. I of course am not running Electron 2.6, but VueJS 2.6 on Electron 13.0.

I haven't yet seen this error before and since it included the keyword linux_x11 I assumed it was something about the native module running in emulation mode which could lead to problems (Some Docker images sure do).

Thank you for giving me a tip where to look though!

**Comment by AryToNeX** [comment]
> since it included the keyword linux_x11 I assumed it was something about the native module running in emulation mode which could lead to problems

There is no native module for Linux, and there is also no native module for macOS. Results are achieved fully using JavaScript and Electron's API.

You encountered an error in a part of the project that will never run on macOS, sadly.
