### ISSUE TITLE
Design discussion: should I replace glasstron.update() with something more convenient?

### ISSUE THREAD

**Issue by AryToNeX** [AryToNeX/Glasstron#7]
As it is now, in order to request blurriness to the system we use `glasstron.update(BrowserWindow, Object)` with Object being nothing more than some key-value pairs ("OS => blur mode").

While this is simple enough at a first glance, I am really looking forward to do things in a more stylish way.

What if, for example, we bind custom methods to the BrowserWindow objects?
```js
browserWindow.setBlur(boolean); // General switch
browserWindow.getBlur(); // Get the current blur status
browserWindow.blurType = string; // determining Windows blur type
```
To me it's way cleaner this way and we can actually achieve it without breaking native casts and anything, really. This could also mean converting a lot of Glasstron classes to static ones or Singletons, saving a bunch of memory.
Plus, we can use the already included `browserWindow.setVibrancy(string|null)` method on macOS, which means that we don't have to deal with macOS for the most part (as we already deal with the setBackgroundColor problem on macOS anyway).

Let me know your thoughts and share your ideas.

**Comment by AryToNeX** [comment]
cc: @sentialx @EnderDev
and sorry for the tag

**Comment by EnderDev** [comment]
Sounds great

**Comment by Bowser65** [comment]
I am usually not a fan of decorating already existing JS objects since it can quickly cause a problem called "prototype pollution" where you don't really know what object you're dealing with (what methods are on this thing??!?11!). It also makes it harder for the editing software to understand what methods are available on an object and makes it harder to have a fluid autocomplete experience. (which is why a lot of eslint configuration do not allow performing such actions, and why lodash is a pile of garbage with prototype pollution CVEs every other day). It could also clash with other libs if somehow they decide to inject w/ the same function name.

As of the memory footprint, since JavaScript is **not** an object oriented programming language but a prototype-based language, the memory footprint of static vs non-static is roughly the same, you'll maybe save a kilobyte or two. The only actual savings this will do is prevent allocating a variable holding an instance of the object, which will just be a reference to the original object (so almost a costless op)

Then it's up to you, whether you feel like decorating the JS object or have something separated to do the work. A mix of those two could be smth like (yes this is es6 you'd need to transpile blblbl whatever)
```js
import Glasstron from 'glasstron'
import { BrowserWindow } from 'electron'

const win = new BrowserWindow({ ... })
const compositor = Glasstron.decorate(win)

compositor.setBlur(...)
console.log(compositor.getBlur())
```
Where the `compositor` would only contain glasstron stuff and `win` still be your average BrowserWindow instance

**Comment by AryToNeX** [comment]
@Bowser65 while the "compositor" object approach is good indeed, it only brings more code to Glasstron (and it makes life much MUCH harder on Glasscord's end). That said, thanks for the little explaination; I will keep the glasstron.update() method for now (maybe I will add a glasstron.get() at some point, to retrieve the current blur status.

**Comment by Bowser65** [comment]
I don't really see how it could cause problems with Glasscord, as each webcontents has its own unique id. You'd just need to keep a map of `id => compositor` in memory which isn't that bad.

Also I don't think more code is obviously a bad thing, especially if it means a cleaner approach and a more user-friendly API for Glasstron. Speaking of cleaner approach, I don't know if extending from Electron's BrowserWindow and patching its exports is a good idea in the case of a tool like Glasstron. It surely gets the job done but it's still a janky approach.

Honestly I'd be okay if Glasstron didn't tweak the transparency setting and it's up to the developer to set it to true. Because then it'd let developers the choice and have for example a toggle in their app to enable or disable composition, and if it's disabled have no Glasstron code getting involved in the process.

**Comment by rauenzi** [comment]
I'd have to agree with Bowser in this case. Since Glasscord/Glasstron is meant to work in tandem with other things, prototype pollution is a real problem. If it was deemed absolutely necessary that the tweaks occurred in Glasscord, then as Bowser said a map with a compositor would be a fine solution.

>  then it'd let developers the choice and have for example a toggle in their app

This would stick with the idea that Glasscord/Glasstron is supplemental

**Comment by sentialx** [comment]
I agree with @Bowser65 User should decide what should happen with transparent property in BrowserWindow and also BrowserWindow can't be extended as it leads to serious electron crashes https://github.com/electron/electron/issues/23

**Comment by Bowser65** [comment]
The fact we can't extend is only partially true (actually more false than true) and you need to fully understand JavaScript objects, Node native binding, how Node/V8 handles them and how Electron fundamentally works and is structured to draw a conclusion on this. Plus this issue is 7 years old and irrelevant with current Electron versions.

With how Glasstron currently handles stuff, extending BrowserWindow doesn't cause any harm since in the end we return the actual "vanilla" BrowserWindow, we don't call super() or anything. It's working without hiccups for everyone I've heard using Glasstron (either directly like dothq, or indirectly like every Glasscord user), not to mention all the Discord client mod using the same injection method.

The only harm it could cause (and it did cause in the past) is breaking some native casts internally if you do call super() and return a modified BrowserWindow (which we don't as of now). No hard crashes, but stuff requiring the native object such as opening GTK modals etc were malfunctioning, which is, yes, a problem.

However, even if it works as I said it's an *injection method* and since in the context of Glasstron since it's made to be a general-purpose lib we can safely consider the developer has full control over the BrowserWindow creation (or at least can gain it through injection) and take care of adding it on their end.

**Comment by AryToNeX** [comment]
@Bowser65

> I don't really see how it could cause problems with Glasscord, as each webcontents has its own unique id. You'd just need to keep a map of `id => compositor` in memory which isn't that bad.

It would be a problem because Glasscord's CSS flags have to work independently of whatever the app requests to Glasstron. Right now, the update method is stubbed if you're using Glasscord on a Glasstron-compatible application (there's a switch for it obvsly)

> Also I don't think more code is obviously a bad thing, especially if it means a cleaner approach and a more user-friendly API for Glasstron. Speaking of cleaner approach, I don't know if extending from Electron's BrowserWindow and patching its exports is a good idea in the case of a tool like Glasstron. It surely gets the job done but it's still a janky approach.

That's the main point of Glasstron: simplicity. "Patching" BrowserWindow means that developers can install the module and use it quickly in their projects, without worrying of patching out stuff and implementing workarounds.

> Honestly I'd be okay if Glasstron didn't tweak the transparency setting and it's up to the developer to set it to true. Because then it'd let developers the choice and have for example a toggle in their app to enable or disable composition, and if it's disabled have no Glasstron code getting involved in the process.

Actually, unless you call glasstron.init() no patching will occur. This means that developers can already do that if they so desire.

Sure, the init() part can be handled better and on a per-platform basis and that's on the TO-DO list.

**Comment by Bowser65** [comment]
I'd disagree with this, you sacrifice a lot of flexibility by extending the BrowserWindow and it makes it difficult to have a per-window composition configuration in a multi-window application. Sometimes you'd want to have a specific window opaque for any reason, or you could have an in-app switch that'd kill the current window and recreate it w/ transparency without restarting the app. Through glasstron.init(), it both cuts off this flexibility and actually causes a bad pattern of having something called in the middle of imports.

If it'd do very complex operations I'd understand there's a benefit, but honestly the only useful things done through injecting are setting transparent to true (and turning the window frameless on windows if necessary). Those are two boolean properties and I am fairly certain developers could handle this without much troubles. Plus, as I mentionned it adds extra flexibility on the way Glasstron behaves and what it does. Moreover it doesn't require completely restarting the app to wipe Glasstron from a BrowserWindow, which is an extra speed boost for apps providing such settings.

As for Glasscord's CSS flags I still don't know where the problem kicks in. When you'd call `Glasstron.decorate`, you save the compositor in a map through the [webContents.id](https://www.electronjs.org/docs/api/web-contents#contentsid-readonly), and then when the webcontents request an update through IPC you just get the message origin, get the appropriated compositor and perform the requested update. Unless I don't fully understand the whole process and I'm missing some steps it's a pretty straightforward process.

`Decorate => Save compositor => Bind events`
`On event => Resolve event origin => Get appropriated compositor => Apply requested updates`

**Comment by AryToNeX** [comment]
> Through glasstron.init(), it both cuts off this flexibility and actually causes a bad pattern of having something called in the middle of imports.

I agree with you there (I wanted to get rid of init() at some point)

> If it'd do very complex operations I'd understand there's a benefit, but honestly the only useful things done through injecting are setting transparent to true (and turning the window frameless on windows if necessary). Those are two boolean properties and I am fairly certain developers could handle this without much troubles. Plus, as I mentionned it adds extra flexibility on the way Glasstron behaves and what it does. Moreover it doesn't require completely restarting the app to wipe Glasstron from a BrowserWindow, which is an extra speed boost for apps providing such settings.

There's actually a problem on macOS with setBackgroundColor(), that's why Glasstron forces transparency and sets the color via CSS. Basically the window would spawn with a black background and it will only "update" to transparent after a manual resize of the window.

> As for Glasscord's CSS flags I still don't know where the problem kicks in.

Imagine this scenario. Someone patches a Glasstron app with Glasscord to achieve CSS loading and more composition flexibility. At some point, the application requests composition effects which override those set by Glasscord via our custom CSS variables. Now, imagine an application having to do this for a very specific reason: how would you handle it?

**Comment by Bowser65** [comment]
> Basically the window would spawn with a black background and it will only "update" to transparent after a manual resize of the window.

Still not a dealbreaker for injection. It's up to developers to not call it and do the background through their app. IMO it should only be required to inject in the event of a complex sequence of instructions added (like sending a bunch of IPCs, calling a bunch of functions, ...) and there's no other way of doing it. The only thing injecting allows is to patch the original options set passed to the BrowserWindow.

There's also the fact that in current Glasstron versions setBackgroundColor is still available since we cannot alter the original BrowserWindow object (native casts memes). So yet again the only thing we're doing is wiping the original background color as set during bw initialization.

> Someone patches a Glasstron app with Glasscord

IMO we should not consider this as a valid use-case of Glasscord, since the blurring part is already handled by Glasstron (sure with limitations from the app regarding customization, but still Glasstron is already there), even though users could benefit from CSS loading.

Also, this would mean `Glasstron.decorate` would be called twice per BrowserWindow (w/ Glasscord injected) which isn't a good idea. Glasstron would have to keep track of every decoration requested and id'd be preferable to avoid it (memory all that).

Moreover, if the compositor gets requests by something other than Glasscord I don't see any cases you want to do it unless you're changing blur as a result of a user interaction. Glasscord and the app clashing that way would mean there's already a way of customizing the compositor built in the app. Sure there's Glasscord's CSS loader which would be handy, but injecting custom css can be done with very little amounts of code so I don't know if it's a big issue.

**Comment by AryToNeX** [comment]
> There's also the fact that in current Glasstron versions setBackgroundColor is still available since we cannot alter the original BrowserWindow object (native casts memes). So yet again the only thing we're doing is wiping the original background color as set during bw initialization.

Actually, that method is currently patched out (BW can be modified as long as we don't mess up the constructor itself)

> > Someone patches a Glasstron app with Glasscord
> 
> IMO we should not consider this as a valid use-case of Glasscord [...]
> Glasscord and the app clashing that way would mean there's already a way of customizing the compositor built in the app. [...]

What if the app has no way to customize the compositor? Actually, I can think of a lot of reasons why this could happen... And anyway, Glasscord ideally runs before the application's code so if we can inject into Glasstron and patch out the compositor export, nothing bad could ever happen. (but again, is that really necessary?)

Time for some ideas now

We could export Glasstron.BrowserWindow without injecting it into Electron's stuff; this way, people could just do:
```js
const glasstron = require("glasstron");
const win = new glasstron.BrowserWindow(options);
```
This will return a "patched" Electron BrowserWindow anyway, but we avoid the injection part this way.

In case someone wants to require Electron, we could make an Utils export with various static functions, one to "patch out" bad options, another one to patch the setBackgroundColor on a BrowserWindow and so on; this way we don't actually have to inject anything but developers can look through the utilities and choose which stuff to pick and use (in case they didn't fix their app for this kind of purpose already)

**Comment by Bowser65** [comment]
I forgot we do update the prototype of the living object, my bad. This can still be achieved through the Glasstron.decorate method since we have direct access to the method though, so it's a non-issue in this case.

As of the apps not having customization settings, as I mentioned the only scenario I can imagine for Glasscord and a native app clashing are if the app does provide composition options (making Glasscord of no use in the compositor customization department).

Exporting the BrowserWindow could be a good idea, however I can see the scenario of the app leaving users the option to enable composition or not have issues with it as it's slightly more annoying to not invoke Glasstron since it needs to build a completely different object.

As for making `glasstron.BrowserWindow` if we do end up with this approach it'd be extremely easy to do it as a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) and pass calls to the actual BrowserWindow when we don't need to do any action. Here's a quick draft of what I have in mind:
```js
import { BrowserWindow as ElectronBW } from 'electron'

class BrowserWindow extends Proxy {
  constructor (opts) {
    this._win = new ElectronBW({
      ...opts,
     transparent: true,
     frame: process.platform === 'win32' ? false : opts.frame
    })

    super(this._win, {
      get (target, prop) {
        switch (prop) {
          case 'setBackgroundColor': return this.setBackgroundColor.bind(this);
          ...
          default: return target[prop];
        }
      }
    })
  }
}
```

Downside of this approach is that the composition stuff still gets merged into the BrowserWindow stuff which isn't the best idea as we discussed earlier.

**Comment by AryToNeX** [comment]
> As of the apps not having customization settings, as I mentioned the only scenario I can imagine for Glasscord and a native app clashing are if the app does provide composition options (making Glasscord of no use in the compositor customization department).

We need to account for every possible scenario anyway, and that is a possible scenario!

> Exporting the BrowserWindow could be a good idea, however I can see the scenario of the app leaving users the option to enable composition or not have issues with it as it's slightly more annoying to not invoke Glasstron since it needs to build a completely different object.

The real problem here is that we cannot modify transparency and initial background color once the object is created. If there was a way to patch those at a later time, we could literally patch out the BW with a single method at any point while the app is running (ultimately giving us extreme flexibility) but hey electron is a meme

**Comment by AryToNeX** [comment]
It has been seventeen days since my last message. I want to clarify the upcoming changes in Glasstron's design.

- Instead of patching Electron's BrowserWindow, Glasstron will provide its own patched module export. This eliminates the need of requiring Glasstron ahead of Electron.
- An Utils class will be made, with all the current "injection and stuff" code. When using methods from this class, developers will be notified through the console that it's better for them if they handle all the stuff themselves (this will be a debug message).
- Glasstron's exports will be just classes. The init() and update() methods will be present and redirected to their Utils counterparts, however those will be removed in just the next version (0.5 I suppose).

The problem now is figuring out how to do it with little damage to Glasscord, which bothers me a little

**Comment by AryToNeX** [comment]
Okay, I am trying to make this happen, however I have a question: what about the actual composition effects?

Exporting Glasstron.BrowserWindow means that we can extend the object; is it fair to write new methods directly in that object? We're falling back to my first suggestion

**Comment by AryToNeX** [comment]
well whatever. Please test what's on the `master` branch please (on Windows / macOS plssss)
